categories:
- Data Managers
description: Build a RepeatModeler database from FASTA files and populate the repeatmodeler_db.loc file.
long_description: ''
name: data_manager_repeatmodeler_db_builder
owner: pvanheus
remote_repository_url: https://github.com/pvanheus/repeatmodeler/tree/master/data_managers/repeatmodeler
type: unrestricted
